import { AuthProvider } from "@/providers/auth";
import { Poppins } from "next/font/google";
import type { Metadata } from "next";

import Header from "@/components/ui/Header";
import "./globals.css";
import Footer from '@/components/ui/Footer';
import { CartProvider } from '@/providers/cart';

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "FSW Store",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <div className="flex h-full flex-col">
          <AuthProvider>
           <CartProvider>
              <Header />
              <div className="flex-1">
                {children}
              </div>
              <Footer />
           </CartProvider>
          </AuthProvider>
        </div>
      </body>
    </html>
  );
}
